Online Car Rental System/Controllers/CarController.cs
using Microsoft.AspNetCore.Mvc;
using Online_Car_Rental_System.Models;
using Online_Car_Rental_System.Services.Interfaces;

namespace Online_Car_Rental_System.Controllers
{
    public class CarController : Controller
    {
        private readonly ICarService _carService;

        public CarController(ICarService carService)
        {
            _carService = carService;
        }
        public IActionResult Index()
        {
            var cars = _carService.GetAllCars();
            return View(cars);
        }

        public IActionResult Create()
        {
            return View();
        }
       

        [HttpPost]
        public IActionResult Create(Car car)
        {
            if(ModelState.IsValid)
            {
                _carService.AddCar(car);
                return RedirectToAction("Index");
            }
            return View(car);
        }

        public IActionResult Edit(int id)
        {
            var car = _carService.GetCarById(id);
            if(car == null)
            {
                return NotFound();
            }
            return View(car);
        }


        [HttpPost]
        public IActionResult Edit(Car car)
        {
            if (ModelState.IsValid)
            {
                _carService.UpdateCar(car);
                return RedirectToAction("Index");
            }
            return View(car);
        }

        public IActionResult Delete(int id)
        {
            _carService.DeleteCar(id);
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            var car = _carService.GetCarById(id);
            if(car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        [HttpGet]
        public JsonResult GetSuggestions(string query)
        {
            var suggestions = _carService.GetSuggestions(query);
            return Json(suggestions);
        }

        [HttpGet]
        public JsonResult GetRecentSearches()
        {
            var recentSearches = _carService.GetRecentSearches();
            return Json(recentSearches);
        }

        public IActionResult Search(string searchTerm)
        {
            var results = _carService.SearchCars(searchTerm);
            if (results == null || !results.Any())
            {
                results = _carService.GetAllCars(); // Assuming you have a method to get all cars
            }
            return View("SearchResults", results);
        }

        public IActionResult Type(string type)
        {
            var cars = _carService.GetCarsByCategory(type);
            return View("SearchResults", cars); 
        }

        public IActionResult Brand(string brand)
        {
            var cars = _carService.GetCarsByBrand(brand);
            return View("SearchResults", cars); 
        }

    }
}

Online Car Rental System/Controllers/ReservationController.cs
using Microsoft.AspNetCore.Mvc;
using Online_Car_Rental_System.Models;
using Online_Car_Rental_System.Services;
using Online_Car_Rental_System.Services.Interfaces;
using Newtonsoft.Json;



namespace Online_Car_Rental_System.Controllers
{
    public class ReservationController : Controller
    {
        private readonly IReservationService _reservationService;
        private readonly ICarService _carService;
        private readonly CarJsonService _carJsonService;

        public ReservationController(IReservationService reservationService, ICarService carService, CarJsonService carJsonService)
        {
            _reservationService = reservationService;
            _carService = carService;
            _carJsonService = carJsonService;
        }

        [HttpGet]
        [Route("Reservation/Create/{carId}")]
        public IActionResult Create(int carId)
        {
            var car = _carService.GetCarById(carId);

            if (car == null)
            {
                return NotFound();
            }

            var viewModel = new ReservationViewModel
            {
                CarId = car.CarId,
                TotalPrice = car.PricePerDay // Assuming you want to initialize TotalPrice with the car's price per day
            };

            ViewBag.Car = car; // Pass the car details to the view using ViewBag
            return View(viewModel);
        }




        [HttpPost]
        public IActionResult Create(ReservationViewModel viewModel)
        {
            var car = _carService.GetCarById(viewModel.CarId);
            if(car.Quantity<viewModel.Quantity)
            {
                ModelState.AddModelError(string.Empty, "The selected car model is no longer available.");
                ViewBag.Car = _carService.GetCarById(viewModel.CarId);
                return View(viewModel);
            }
            if (ModelState.IsValid)
            {
                var reservation = new Reservation
                {
                    CarId = viewModel.CarId,
                    Name = viewModel.Name,
                    UserEmail = viewModel.UserEmail,
                    MobileNumber = viewModel.MobileNumber,
                    HasValidDriverLicense = viewModel.HasValidDriverLicense,
                    RentStartDate = viewModel.RentStartDate,
                    RentEndDate = viewModel.RentEndDate,
                    Quantity = viewModel.Quantity,
                    TotalPrice = viewModel.TotalPrice,
                    Status = "Unconfirmed", // Default status
                    SessionId = HttpContext.Session.Id // Set the SessionId

                };


                _reservationService.AddReservation(reservation);
                return RedirectToAction("Details", new { id = reservation.ReservationId });
            }
            return View(viewModel);
        }

        public IActionResult Edit(int id)
        {
            var reservation = _reservationService.GetReservationById(id);
            if(reservation == null)
            {
                return NotFound();
            }
            var viewModel = new ReservationViewModel
            {
                ReservationId = reservation.ReservationId,
                CarId = reservation.CarId,
                Name = reservation.Name,
                UserEmail = reservation.UserEmail,
                MobileNumber = reservation.MobileNumber,
                HasValidDriverLicense = reservation.HasValidDriverLicense,
                RentStartDate = reservation.RentStartDate,
                RentEndDate = reservation.RentEndDate,
                Quantity = reservation.Quantity,
                TotalPrice = reservation.TotalPrice
            };
            ViewBag.Car = _carService.GetCarById(reservation.CarId); // Pass the car details to the view using ViewBag
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Edit(ReservationViewModel viewModel)
        {
           if (ModelState.IsValid)
            {
                var reservation = _reservationService.GetReservationById(viewModel.ReservationId);
                if(reservation == null)
                {
                    return NotFound();
                }

                reservation.Name = viewModel.Name;
                reservation.UserEmail = viewModel.UserEmail;
                reservation.MobileNumber = viewModel.MobileNumber;
                reservation.HasValidDriverLicense = viewModel.HasValidDriverLicense;
                reservation.RentStartDate = viewModel.RentStartDate;
                reservation.RentEndDate = viewModel.RentEndDate;
                reservation.Quantity = viewModel.Quantity;
                reservation.TotalPrice = viewModel.TotalPrice;
                _reservationService.UpdateReservation(reservation);
                return RedirectToAction("Details", new {id= reservation.ReservationId});
            }
            ViewBag.Car = _carService.GetCarById(viewModel.CarId); // Pass the car details to the view using ViewBag
            return View(viewModel);

        }

        public IActionResult Details(int id)
        {
            var reservation = _reservationService.GetReservationById(id);
            if(reservation == null)
            {
                return NotFound();
            }
            return View(reservation);
        }

       

        public IActionResult Delete(int id)
        {
            _reservationService.DeleteReservation(id);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Recent()
        {
            string sessionId = HttpContext.Session.Id; // Get the current session ID
            var reservation = _reservationService.GetMostRecentUncompletedReservation();
            if (reservation == null)
            {
                return RedirectToAction("Create");
            }

            var car = _carService.GetCarById(reservation.CarId);
            ViewBag.Car = car;
            return View("Details", reservation);
        }

        public IActionResult Confirm(int id)
        {
            var reservation = _reservationService.GetReservationById(id);
            if(reservation == null)
            {
                return NotFound();
            }
            reservation.Status = "Confirmed";
            _reservationService.UpdateReservation(reservation);

            //Update car Availability
            var car = _carService.GetCarById(reservation.CarId);
            car.Quantity -= reservation.Quantity;
            _carService.UpdateCar(car);

            //Update the car data in JSON
            _carJsonService.UpdateJsonFile(_carService.GetAllCars());
            
            return RedirectToAction("Details", new {id = reservation.ReservationId});   
        }

        // GET: Reservation/Cancel
        public IActionResult Cancel()
        {
            // Clear reservation information if necessary
            // This can be done by clearing session data, if used

            // Redirect to homepage
            return RedirectToAction("Index", "Home");
        }

        // GET: Reservation/Confirmation
        public IActionResult Confirmation(int id)
        {
            var reservation = _reservationService.GetReservationById(id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }


    }
}

Online Car Rental System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Online_Car_Rental_System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/home.css" asp-append-version="true" /> <!-- Include home.css -->
    <link rel="stylesheet" href="~/Online_Car_Rental_System.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @*
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Online_Car_Rental_System</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
        <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </li>
        </ul>
        </div>
        </div>
        </nav>
        *@
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white  box-shadow mb-3">
            <div class="container nav-container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/logoTransparent.png" alt="Online Grocery Store Logo">
                </a>
                @if (!ViewData.ContainsKey("HideSearchBox"))
                {
                    <form class="form-inline my-2 my-lg-0 d-flex align-items-center gap-1" asp-controller="Car" asp-action="Search" method="get">
                        <input class="form-control form-control-sm search-box" type="search" placeholder="Search Cars" aria-label="Search" name="searchTerm" id="searchInput">
                        <button class="btn search-button" type="submit">Search</button>
                        <div id="searchSuggestions" class="suggestions-box d-none"></div>
                    </form>
                }
                @if (!ViewData.ContainsKey("HideUL"))
                {
                    <ul class="nav-link">
                        <li><a href="@Url.Action("Index", "Home")" style="--i:1;">Home</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="typeDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="--i:2;">Type</a>
                            <div class="dropdown-menu" aria-labelledby="typeDropdown">
                                <a class="dropdown-item" asp-controller="Car" asp-action="Type" asp-route-type="Sedan">Sedan</a>
                                <a class="dropdown-item" asp-controller="Car" asp-action="Type" asp-route-type="Wagon">Wagon</a>
                                <a class="dropdown-item" asp-controller="Car" asp-action="Type" asp-route-type="SUV">SUV</a>
                                <!-- Add more types as needed -->
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="brandDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="--i:3;">Brand</a>
                            <div class="dropdown-menu" aria-labelledby="brandDropdown">
                                <a class="dropdown-item" asp-controller="Car" asp-action="Brand" asp-route-brand="Ford">Ford</a>
                                <a class="dropdown-item" asp-controller="Car" asp-action="Brand" asp-route-brand="Mazda">Mazda</a>
                                <a class="dropdown-item" asp-controller="Car" asp-action="Brand" asp-route-brand="BMW">BMW</a>
                                <!-- Add more brands as needed -->
                            </div>
                        </li>
                        <li><a href="@Url.Action("Recent", "Reservation")" style="--i:4;">Reservation</a></li>
                    </ul>

                }

                <!--<ul class="social-link">
                    <li><a href="#" style="--i:1;"><i class="fab fa-facebook"></i></a></li>
                    <li><a href="#" style="--i:2;"><i class="fab fa-twitter"></i></a></li>
                    <li><a href="#" style="--i:3;"><i class="fab fa-instagram"></i></a></li>
                </ul>-->
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class=" border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Online_Car_Rental_System - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script>
        // Example to save session ID in local storage (if needed)
        document.addEventListener("DOMContentLoaded", function () {
            if (!localStorage.getItem("sessionId")) {
                localStorage.setItem("sessionId", "@Context.Session.Id");
            }
        });
    </script>
</body>
</html>